name: fullfluttersetup
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  async: ^2.11.0
  auto_route: ^8.0.3
  auto_route_generator: ^8.0.0
  bloc: ^8.1.3
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.3.1
  connectivity_plus: ^3.0.6
  dartz: ^0.10.1
  data_channel: ^2.0.0+1
  device_info_plus: ^10.1.0
  dio: ^5.4.2+1
  encrypted_shared_preferences: ^3.0.1
  equatable: ^2.0.5
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  flutter_bloc: ^8.1.5
  flutter_displaymode: ^0.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_nfc_kit: ^3.3.3
  flutter_overlay_apps: ^1.2.0
  flutter_overlay_window: ^0.4.4
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  fresh_dio: ^0.4.1
  get_it: ^7.6.8
  graphql_flutter: ^5.0.0-nullsafety.5
  http: ^0.13.6
  image_pickers: ^2.0.4+10
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.4.1
  injectable_generator: ^2.6.1
  internet_connection_checker: ^1.0.0+1
  internet_connection_checker_plus: ^1.0.1
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  json_annotation: ^4.8.1
  json_theme: ^6.4.0
  material_design_icons_flutter: ^7.0.7296
  path_provider: ^2.1.2
  path_provider_android: ^2.2.2
  permission_handler: ^11.3.1
  pinput: ^4.0.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  stream_transform: ^2.1.0
  url_launcher: ^6.2.6
  web_socket_channel: ^2.4.4
  # flutter_lints: ^3.0.1
  # flutter_native_splash: ^2.4.0
  # internet_connection_checker: ^1.0.0+1
  # firebase_core: ^2.27.1
  # firebase_messaging: ^14.7.20

dev_dependencies:
  # flutter_gen_runner: ^5.2.0
  bloc_test: ^9.1.6
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/

flutter_gen:
  output: lib/gen/
  line_length: 50 # Optional (default: 80)
  integrations:
    flutter_svg: true
    flare_flutter: true
  assets:
    enabled: true
    outputs:
      class_name: MyAssets
      package_parameter_enabled: false
      style: dot-delimiter

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/send.png
  # branding: assets/branding-development.png
  # color_dark: "#121212"
  # image_dark: assets/logo-development.png
  # branding_dark: assets/branding-development.png

  android_12:
    image: assets/icons/send.png
    icon_background_color: "#ffffff"
    # image_dark: assets/logo-development.png
    # icon_background_color_dark: "#121212"
